language: php
php:
  - '5.6'
  - '7.0'

install:
  - composer install

script:
  - ./vendor/bin/phpunit
  - bin/atoum --test-all

notifications:
  email:
    recipients:
      - otaviobpinto@gmail.com
    on_success: never
    on_failure: always
