version: 2

jobs:
  test-7.2:
    docker:
      - image: cimg/php:7.2

    steps:
      - checkout
      - run: sudo apt update
      - run: composer install -n --prefer-dist

      # run tests with phpunit
      - run: ./vendor/bin/phpunit
