version: 2

jobs:
  test-7.2:
    docker:
      - image: cimg/php:7.2

    steps:
      - checkout
      - run: sudo apt update
      - run: composer install -n --prefer-dist

      # run tests with phpunit
      - run: ./vendor/bin/phpunit
  test-7.3:
    docker:
      - image: cimg/php:7.3

    steps:
      - checkout
      - run: sudo apt update
      - run: composer install -n --prefer-dist

      # run tests with phpunit
      - run: ./vendor/bin/phpunit
  test-7.4:
    docker:
      - image: cimg/php:7.4

    steps:
      - checkout
      - run: sudo apt update
      - run: composer install -n --prefer-dist

      # run tests with phpunit
      - run: ./vendor/bin/phpunit
  test-8.0:
    docker:
      - image: cimg/php:8.0

    steps:
      - checkout
      - run: sudo apt update
      - run: composer install -n --prefer-dist

      # run tests with phpunit
      - run: ./vendor/bin/phpunit
  test-8.1:
    docker:
      - image: cimg/php:8.1

    steps:
      - checkout
      - run: sudo apt update
      - run: composer install -n --prefer-dist

      # run tests with phpunit
      - run: ./vendor/bin/phpunit
  test-8.2:
    docker:
      - image: cimg/php:8.2

    steps:
      - checkout
      - run: sudo apt update
      - run: composer install -n --prefer-dist

      # run tests with phpunit
      - run: ./vendor/bin/phpunit

workflows:
  version: 2

  workflow:
    jobs:
      - test-7.2
      - test-7.3
      - test-7.4
      - test-8.0
      - test-8.1
      - test-8.2
