name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  composer-check:
    name: Composer Check

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

  unit-test:
    name: Unit Test

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
        - '7.2'
        - '7.3'
        - '7.4'

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      uses: php-actions/phpunit@v3
      with:
        version: 6.0
        php_version: ${{ matrix.php-version }}
        php_extensions: xdebug
        configuration: phpunit.xml
        args: --coverage-clover build/logs/clover.xml
      env:
        XDEBUG_MODE: coverage

    - name: Coveralls
      run: php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v --json_path=build/logs/coveralls-upload.json
      env:
        COVERALLS_RUN_LOCALLY: ${{secrets.COVERALLS_RUN_LOCALLY}}
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}

